# Notebook 6 – Data Inspection


In [1]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(42)  # fixed seed -> reproducible "random" data

n = 60  # number of orders

regions = ["North", "South", "East", "West"]
products = ["Laptop", "Monitor", "Keyboard", "Mouse", "Headphones", "Webcam"]
categories = {"Laptop": "Computers", "Monitor": "Computers", "Keyboard": "Accessories",
              "Mouse": "Accessories", "Headphones": "Accessories", "Webcam": "Accessories"}
payment_methods = ["Credit Card", "PayPal", "Bank Transfer", "Cash"]

product_choice = rng.choice(products, size=n)

df = pd.DataFrame({
    "OrderID": np.arange(1001, 1001 + n),
    "CustomerName": [f"Customer_{i}" for i in rng.integers(1, 35, size=n)],
    "Region": rng.choice(regions, size=n),
    "Product": product_choice,
    "Category": [categories[p] for p in product_choice],
    "Quantity": rng.integers(1, 10, size=n),
    "UnitPrice": np.round(rng.uniform(15, 1500, size=n), 2),
    "OrderDate": pd.to_datetime("2025-01-01") + pd.to_timedelta(rng.integers(0, 180, size=n), unit="D"),
    "PaymentMethod": rng.choice(payment_methods, size=n),
})

df["Sales"] = np.round(df["Quantity"] * df["UnitPrice"], 2)

# Introduce some realistic messiness: a few missing values
missing_idx = rng.choice(df.index, size=5, replace=False)
df.loc[missing_idx, "PaymentMethod"] = np.nan

missing_idx2 = rng.choice(df.index, size=3, replace=False)
df.loc[missing_idx2, "UnitPrice"] = np.nan
df.loc[missing_idx2, "Sales"] = np.nan

df.head()

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
0,1001,Customer_32,South,Laptop,Computers,9,882.39,2025-06-02,Cash,7941.51
1,1002,Customer_26,East,Headphones,Accessories,2,980.02,2025-06-10,Bank Transfer,1960.04
2,1003,Customer_13,East,Mouse,Accessories,5,140.40,2025-02-10,Cash,702.00
3,1004,Customer_33,South,Keyboard,Accessories,7,632.47,2025-06-10,Bank Transfer,4427.29
4,1005,Customer_14,West,Keyboard,Accessories,5,76.80,2025-01-21,PayPal,384.00


## 1. `head()`
`head()` returns the **first N rows** of a DataFrame (default N = 5). It's the quickest way to peek at the *shape and content* of your data — the column names, the kind of values stored in them, and roughly how the rows are formatted — without printing the entire dataset, which could be thousands or millions of rows.

### Demonstration
**Real-world analogy:** Think of `head()` like reading the first page of a book, or opening the first few emails at the top of your inbox. You don't read the whole book to decide if it's interesting — the first page tells you enough about the tone, characters, and setting to orient yourself. Similarly, `head()` orients you to a dataset before you commit to deeper analysis.

**Business example:** A retail analyst receives a sales export with 50,000 rows. Before writing any code to clean or analyze it, they run `df.head()` to sanity-check that the columns loaded correctly (right delimiter, right headers, dates not mangled, etc.).

In [2]:
# Show the first 5 rows (default)
df.head()

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
0,1001,Customer_32,South,Laptop,Computers,9,882.39,2025-06-02,Cash,7941.51
1,1002,Customer_26,East,Headphones,Accessories,2,980.02,2025-06-10,Bank Transfer,1960.04
2,1003,Customer_13,East,Mouse,Accessories,5,140.40,2025-02-10,Cash,702.00
3,1004,Customer_33,South,Keyboard,Accessories,7,632.47,2025-06-10,Bank Transfer,4427.29
4,1005,Customer_14,West,Keyboard,Accessories,5,76.80,2025-01-21,PayPal,384.00


In [3]:
# You can pass a custom number of rows
df.head(3)

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
0,1001,Customer_32,South,Laptop,Computers,9,882.39,2025-06-02,Cash,7941.51
1,1002,Customer_26,East,Headphones,Accessories,2,980.02,2025-06-10,Bank Transfer,1960.04
2,1003,Customer_13,East,Mouse,Accessories,5,140.40,2025-02-10,Cash,702.00


**What the code does:** Displays the first 5 (or however many are requested) rows of `df`, including all columns.

**Why it's used:** It's the fastest sanity check after loading data — confirming columns parsed correctly, spotting obvious issues like NaNs or wrong data types, and understanding what each column represents.

**Expected output:** A small table with 5 (or `n`) rows and all 10 columns of our sales dataset (OrderID, CustomerName, Region, ... Sales).

**Where it's used in AI/ML / Data Analytics:** It is almost always the *first line of code* run after loading any dataset in a notebook — before feature engineering, before EDA, before model training — to confirm the data "looks right."

## 2. `tail()`

`tail()` is the mirror image of `head()` — it returns the **last N rows** of a DataFrame (default N = 5). It's useful for checking the *end* of a dataset, which `head()` alone can't reveal.

###  Demonstration
**Real-world analogy:** If `head()` is reading the first page of a book, `tail()` is flipping to the last page to see how the story ends. In data terms, it lets you check things `head()` can't — for example, whether a time-series dataset actually extends to the date you expect, or whether the last rows of an appended file got cut off or corrupted.

**Simple example:** If you append new records to a growing sales log every day, `tail()` shows you the most recently added orders — a quick way to confirm today's data actually made it in.

In [4]:
# Show the last 5 rows
df.tail()

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
55,1056,Customer_20,South,Laptop,Computers,7,NaN,2025-05-02,Cash,NaN
56,1057,Customer_2,East,Mouse,Accessories,6,661.12,2025-06-24,Cash,3966.72
57,1058,Customer_5,North,Laptop,Computers,4,1488.68,2025-01-22,Credit Card,5954.72
58,1059,Customer_9,West,Headphones,Accessories,3,1339.14,2025-02-23,NaN,4017.42
59,1060,Customer_4,East,Headphones,Accessories,6,1126.68,2025-04-02,Credit Card,6760.08


In [5]:
# Last 3 rows only
df.tail(3)

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
57,1058,Customer_5,North,Laptop,Computers,4,1488.68,2025-01-22,Credit Card,5954.72
58,1059,Customer_9,West,Headphones,Accessories,3,1339.14,2025-02-23,NaN,4017.42
59,1060,Customer_4,East,Headphones,Accessories,6,1126.68,2025-04-02,Credit Card,6760.08


**What the code does:** Displays the final rows of `df`.

**Why it's used:** Confirms the dataset wasn't truncated, checks the most recent entries in time-ordered data, and verifies that concatenation/appending operations worked as expected.

**Expected output:** The last 5 (or 3) rows, with `OrderID` values near the top of the ID range (e.g., 1057–1060).

**Where it's used in AI/ML / Data Analytics:** Common in time-series work (checking the most recent dates are present), and in pipeline debugging (confirming a merge or append didn't silently drop the tail of the data).

## 3. `sample()`

`sample()` returns a **random subset of rows**, rather than rows from a fixed position like `head()`/`tail()`. This matters because the first or last rows of a dataset are sometimes not representative — for instance, if the data is sorted by date, region, or category, `head()` might show you only one region's worth of records.

### Demonstration
**Real-world analogy:** Imagine a factory quality inspector checking product quality. Instead of inspecting only the first 5 items off the line (which might all come from the same well-calibrated early batch), they pull random items throughout the day — a more representative and unbiased check.

**AI/ML use case:** When exploring a dataset before model training, `sample()` avoids the bias of "structured" viewing — if your data is sorted by class label, `head()` might show only "class A" rows, making you think there's no class imbalance when there is.

In [6]:
# Random sample of 5 rows (fixed seed so it's reproducible in this notebook)
df.sample(5, random_state=42)

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
0,1001,Customer_32,South,Laptop,Computers,9,882.39,2025-06-02,Cash,7941.51
5,1006,Customer_12,East,Webcam,Accessories,5,748.58,2025-04-04,Credit Card,3742.90
36,1037,Customer_9,North,Webcam,Accessories,1,432.63,2025-01-09,Credit Card,432.63
45,1046,Customer_27,West,Webcam,Accessories,3,565.82,2025-04-01,Cash,1697.46
13,1014,Customer_5,East,Headphones,Accessories,4,530.10,2025-03-09,Credit Card,2120.40


In [7]:
# Random 20% of the rows
df.sample(frac=0.2, random_state=1)

,OrderID,CustomerName,Region,Product,Category,Quantity,UnitPrice,OrderDate,PaymentMethod,Sales
39,1040,Customer_5,West,Mouse,Accessories,9,1156.44,2025-02-25,Credit Card,10407.96
41,1042,Customer_7,East,Headphones,Accessories,5,1375.28,2025-05-20,Credit Card,6876.40
2,1003,Customer_13,East,Mouse,Accessories,5,140.40,2025-02-10,Cash,702.00
48,1049,Customer_17,South,Headphones,Accessories,5,485.95,2025-06-18,Credit Card,2429.75
50,1051,Customer_10,North,Headphones,Accessories,5,447.01,2025-02-01,Bank Transfer,2235.05
44,1045,Customer_28,South,Laptop,Computers,7,838.96,2025-03-31,Credit Card,5872.72
33,1034,Customer_14,South,Mouse,Accessories,5,837.74,2025-04-18,Credit Card,4188.70
35,1036,Customer_10,East,Laptop,Computers,3,NaN,2025-06-07,Bank Transfer,NaN
40,1041,Customer_29,West,Laptop,Computers,2,175.00,2025-06-29,Bank Transfer,350.00
27,1028,Customer_11,North,Headphones,Accessories,9,788.20,2025-05-30,NaN,7093.80


**What the code does:** Randomly selects rows from `df` — either a fixed count (`n=5`) or a fraction of the dataset (`frac=0.2`). `random_state` fixes the random seed so results are reproducible.

**Why it's used:** Gives an unbiased snapshot of the data, especially useful when rows are sorted or grouped in some way that would make `head()`/`tail()` misleading.

**Expected output:** 5 rows (or 20% of all rows) picked at random from anywhere in the DataFrame — different rows each time you run it, unless `random_state` is fixed.

**Where it's used in AI/ML / Data Analytics:** Quick unbiased EDA checks, and conceptually it's the same idea behind **train/test splitting** and **bootstrap sampling** — pulling a random subset to represent the whole population.

## 4. `info()`
`info()` gives a **structural summary** of the DataFrame: the number of rows, the list of columns, how many non-null (non-missing) values each column has, the data type of each column, and total memory usage. It answers "what is this dataset made of?" rather than "what does it contain?" — that's the job of `head()`.

###  Demonstration
**Real-world analogy:** `info()` is like the spec sheet on the back of a product box — it doesn't show you the product itself, but tells you its dimensions, materials, and weight. Similarly, `info()` tells you the "shape and material" of your data (types, size, missingness) rather than the actual values.

**Business example:** A data engineer receiving a new CSV feed from a partner runs `df.info()` first to check whether numeric columns actually loaded as numbers (`int64`/`float64`) rather than text (`object`), and whether any column has fewer non-null values than expected — an early warning sign of missing data.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   OrderID        60 non-null     int64         
 1   CustomerName   60 non-null     object        
 2   Region         60 non-null     object        
 3   Product        60 non-null     object        
 4   Category       60 non-null     object        
 5   Quantity       60 non-null     int64         
 6   UnitPrice      57 non-null     float64       
 7   OrderDate      60 non-null     datetime64[ns]
 8   PaymentMethod  55 non-null     object        
 9   Sales          57 non-null     float64       
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 4.8+ KB


**What the code does:** Prints, for each column: its name, count of non-null values, and dtype; plus overall row/column counts and memory footprint.

**Why it's used:** It's the fastest way to catch two of the most common real-world data problems: **wrong data types** (e.g., a date stored as text) and **missing values** (a column with fewer non-null entries than total rows).


## 5. `describe()`

`describe()` computes **summary statistics** for the numeric columns of a DataFrame by default — count, mean, standard deviation, min, max, and the 25th/50th/75th percentiles. It condenses potentially thousands of numbers into a handful of statistics that describe the overall distribution.

### Demonstration
**Real-world analogy:** If a teacher hands back 60 exam papers, `describe()` is like the summary at the top of the gradebook: average score, highest, lowest, and how spread out the scores are — without you having to read all 60 papers individually.

**AI/ML use case:** Before scaling/normalizing features for a machine learning model, `describe()` reveals which columns have very different ranges (e.g., `Quantity` in single digits vs `Sales` in the thousands) — a strong hint that feature scaling is needed.

In [9]:
# Summary statistics for numeric columns
df.describe()

,OrderID,Quantity,UnitPrice,OrderDate,Sales
count,60.000000,60.000000,57.000000,60,57.000000
mean,1030.500000,5.083333,743.960175,2025-03-24 00:00:00,3888.464386
min,1001.000000,1.000000,47.090000,2025-01-01 00:00:00,48.860000
25%,1015.750000,3.000000,411.460000,2025-02-01 18:00:00,1297.200000
50%,1030.500000,5.000000,743.700000,2025-03-09 12:00:00,3551.660000
75%,1045.250000,7.000000,1126.680000,2025-05-16 00:00:00,6048.140000
max,1060.000000,9.000000,1488.680000,2025-06-29 00:00:00,10407.960000
std,17.464249,2.374238,439.199208,NaN,2915.135721


In [10]:
# Summary for categorical (object) columns instead
df.describe(include='object')

,CustomerName,Region,Product,Category,PaymentMethod
count,60,60,60,60,55
unique,30,4,6,2,4
top,Customer_24,East,Headphones,Accessories,Credit Card
freq,4,17,16,45,16


**What the code does:** The first call computes count/mean/std/min/25%/50%/75%/max for every numeric column (`Quantity`, `UnitPrice`, `Sales`). The second call, using `include='object'`, instead summarizes text/categorical columns with count, number of unique values, the most frequent value (`top`), and its frequency (`freq`).

**Why it's used:** It's the quickest way to understand the *distribution and scale* of your numeric data (spotting outliers, skew, or unexpected ranges) and the *diversity* of your categorical data, all in one call.

**Expected output:** A table where each numeric column has 8 statistics; for `Sales`, you'd expect a `count` slightly below 60 (because of the missing values we introduced), a `mean` around a few hundred to low thousands, and a `max` well above the mean (since some laptops sold in bulk).

**Where it's used in AI/ML / Data Analytics:** Core EDA step used to detect outliers, decide on scaling/normalization strategies, and check for logically invalid values (e.g., negative prices, which would show up as a suspicious `min`).

## 6. `shape`

`shape` is an **attribute** (not a method — no parentheses) that returns a tuple `(number_of_rows, number_of_columns)`. It's the fastest possible way to know the size of a dataset.

### Demonstration
**Real-world analogy:** `shape` is like asking "how many pages and how many columns per page does this spreadsheet have?" without opening it — just checking the file's dimensions.

**Simple example:** After filtering a DataFrame (e.g., keeping only orders from the "North" region), checking `.shape` immediately tells you how many rows survived the filter, without printing the data.

In [11]:
df.shape

(60, 10)

In [12]:
rows, cols = df.shape
print(f"The dataset has {rows} rows and {cols} columns.")

The dataset has 60 rows and 10 columns.


**What the code does:** Returns a tuple of `(rows, columns)`, which can be unpacked into two variables.

**Why it's used:** It's a near-instant way to verify dataset size — especially useful for confirming that a filter, merge, or groupby produced the expected number of rows.

**Expected output:** `(60, 10)` — 60 rows (orders) and 10 columns.

**Where it's used in AI/ML / Data Analytics:** Used constantly to verify train/test split sizes (e.g., confirming `X_train.shape[0]` matches `y_train.shape[0]`), and to sanity-check that a data cleaning step didn't unexpectedly drop rows.

## 7. `columns`

`columns` is an attribute that returns the **column labels** of the DataFrame as an Index object (which behaves much like a list). It tells you exactly what fields are available, in what order.

### Demonstration
**Real-world analogy:** `columns` is like the header row of a spreadsheet, or the table of contents of a report — it tells you what topics/fields exist before you look at any actual data.

**Business example:** When integrating data from multiple departments, an analyst checks `df.columns` to confirm the column naming convention (e.g., `OrderID` vs `order_id`) before merging with another dataset — mismatched naming is one of the most common causes of failed joins.

In [13]:
df.columns

Index(['OrderID', 'CustomerName', 'Region', 'Product', 'Category', 'Quantity',
       'UnitPrice', 'OrderDate', 'PaymentMethod', 'Sales'],
      dtype='object')

In [14]:
# Convert to a plain Python list, and rename programmatically (e.g., lowercase, no spaces)
list(df.columns)

['OrderID',
 'CustomerName',
 'Region',
 'Product',
 'Category',
 'Quantity',
 'UnitPrice',
 'OrderDate',
 'PaymentMethod',
 'Sales']

**What the code does:** Returns the column names of `df` as a pandas Index; converting with `list()` gives an ordinary Python list.

**Why it's used:** To inspect available fields, check naming conventions before merging datasets, or to programmatically loop over/rename columns (e.g., `df.columns = df.columns.str.lower()`).


**Where it's used in AI/ML / Data Analytics:** Used when programmatically selecting feature columns for a model (e.g., `feature_cols = [c for c in df.columns if c != 'target']`), or standardizing column names across multiple data sources before combining them.

## 8. `dtypes`

`dtypes` is an attribute that shows the **data type of every column** — e.g., `int64` (whole numbers), `float64` (decimals), `object` (usually text), `datetime64[ns]` (dates/times), `bool`, or `category`. This is narrower than `info()`, which shows dtypes *plus* non-null counts and memory — `dtypes` shows *only* the types.

### Demonstration
**Real-world analogy:** Think of `dtypes` like checking the unit of measurement on a set of lab instruments — is this reading in kilograms or pounds? Is this field a number I can do math on, or just a text label? Getting this wrong (e.g., treating a date column as text) leads to bugs later.

**AI/ML use case:** Many ML algorithms require purely numeric input. Checking `dtypes` immediately reveals which columns (like `Region`, `Product`, `PaymentMethod` — all `object`) will need encoding (e.g., one-hot encoding) before they can be fed into a model.

In [15]:
df.dtypes

,0
OrderID,int64
CustomerName,object
Region,object
Product,object
Category,object
Quantity,int64
UnitPrice,float64
OrderDate,datetime64[ns]
PaymentMethod,object
Sales,float64


In [16]:
# Count how many columns fall into each data type
df.dtypes.value_counts()

,count
object,5
int64,2
float64,2
datetime64[ns],1


**What the code does:** The first line lists the dtype of every column. The second line (combining `dtypes` with `value_counts()`, covered next) tallies how many columns share each type.

**Why it's used:** To quickly identify which columns are numeric (ready for math/statistics), which are text/categorical (may need encoding), and which are dates (may need `pd.to_datetime()` conversion if not already parsed).

**Expected output:** `OrderID` → `int64`, `Quantity` → `int64`, `UnitPrice`/`Sales` → `float64`, `OrderDate` → `datetime64[ns]`, and `CustomerName`/`Region`/`Product`/`Category`/`PaymentMethod` → `object`.

**Where it's used in AI/ML / Data Analytics:** Directly informs preprocessing decisions — numeric columns might get scaled, `object` columns get encoded (one-hot/label encoding), and `datetime64` columns get decomposed into features like day-of-week or month.

## 9. `memory_usage()`

`memory_usage()` reports how much **RAM** each column consumes, in bytes. By default it also includes a small overhead entry for the DataFrame's index. Passing `deep=True` gives an accurate reading for `object` (text) columns, since Python strings have variable, non-obvious memory footprints that a shallow scan underestimates.

### Demonstration
**Real-world analogy:** `memory_usage()` is like weighing individual boxes before loading a moving truck — it tells you exactly which "boxes" (columns) are heaviest, so you know where to focus if you need to lighten the load.

**Business example:** A data team working with a 5-million-row customer dataset uses `memory_usage(deep=True)` to discover that a single `object` (text) column of free-form notes is consuming 70% of the DataFrame's memory — prompting them to either drop it, truncate it, or convert it to a more efficient `category` dtype.

In [17]:
df.memory_usage()

,0
Index,132
OrderID,480
CustomerName,480
Region,480
Product,480
Category,480
Quantity,480
UnitPrice,480
OrderDate,480
PaymentMethod,480


In [18]:
# More accurate for text/object columns
df.memory_usage(deep=True)

,0
Index,132
OrderID,480
CustomerName,3586
Region,3209
Product,3384
Category,3570
Quantity,480
UnitPrice,480
OrderDate,480
PaymentMethod,3333


In [19]:
# Total memory usage in kilobytes
total_kb = df.memory_usage(deep=True).sum() / 1024
print(f"Total memory usage: {total_kb:.2f} KB")

Total memory usage: 19.15 KB


**What the code does:** Returns the number of bytes used by each column (plus the index); `deep=True` walks into `object` columns to measure actual string sizes rather than just pointer sizes; summing and dividing by 1024 converts bytes to kilobytes.

**Why it's used:** Critical for working with large datasets where RAM is a constraint — helps decide which columns to downcast (e.g., `int64` → `int32`), convert to `category`, or drop entirely.

**Expected output:** A Series with one entry per column (plus `Index`), each an integer byte count; the deep version will show noticeably larger numbers for `object` columns like `CustomerName` and `Region` than the shallow version does.

**Where it's used in AI/ML / Data Analytics:** Common in performance-tuning big datasets before model training — e.g., converting low-cardinality text columns (like `Region`, which only has 4 unique values) to the `category` dtype can cut memory usage dramatically.

## 10. `nunique()`

`nunique()` counts the number of **unique (distinct) values** in each column (or in a single Series). It answers "how much variety does this column actually have?" — which is different from `count()` (which just counts non-null values, including repeats).

### Demonstration
**Real-world analogy:** If a teacher asks "how many different countries do the students in this class come from?", they're not asking for a headcount of students (that's `count()`), they're asking for the number of *distinct* countries — that's exactly what `nunique()` computes.

**AI/ML use case:** `nunique()` is one of the first checks before one-hot encoding a categorical column — a column with 3 unique values is cheap to encode, but a column (like a raw "customer ID" or "free-text comment") with thousands of unique values would blow up the feature space if encoded the same way, so a different approach is needed.

In [20]:
# Number of unique values per column
df.nunique()

,0
OrderID,60
CustomerName,30
Region,4
Product,6
Category,2
Quantity,9
UnitPrice,57
OrderDate,53
PaymentMethod,4
Sales,57


In [21]:
# Number of unique values in a single column
df['Region'].nunique()

4

**What the code does:** The first line reports, column by column, how many distinct values it contains. The second focuses on just the `Region` column.

**Why it's used:** To assess *cardinality* — low-cardinality columns (like `Region` with 4 values, or `PaymentMethod` with 4 values) are good candidates for one-hot encoding or the `category` dtype; high-cardinality columns (like `OrderID`, which is unique per row) usually aren't useful as categorical features at all.

**Expected output:** `OrderID` → 60 (all unique, since it's an ID), `Region` → 4, `Product` → 6, `Category` → 2, `PaymentMethod` → 4 (plus missing values, which `nunique()` excludes by default).

**Where it's used in AI/ML / Data Analytics:** Directly guides feature engineering decisions — deciding between one-hot encoding, target encoding, or dropping a column entirely, based on how many distinct categories it has.

## 11. `value_counts()`

`value_counts()` goes one step further than `nunique()` — instead of just *counting* how many unique values exist, it shows **each unique value along with how often it occurs**, sorted from most to least frequent by default. It's the go-to method for understanding the *distribution* of a categorical column.

###  Demonstration
**Real-world analogy:** If `nunique()` tells you "this class has students from 5 different countries," `value_counts()` tells you *how many* students come from each country — e.g., "12 from Finland, 8 from Sweden, 3 from Norway..." It's the difference between knowing the categories exist and knowing how the data is actually distributed across them.

**Business example:** A retail manager runs `value_counts()` on the `PaymentMethod` column to see that 70% of customers pay by credit card and almost no one pays by bank transfer — informing a decision about which payment partners to prioritize for a checkout redesign.

In [22]:
# Frequency of each Region
df['Region'].value_counts()

,count
Region,
East,17
South,16
West,14
North,13


In [23]:
# As proportions instead of raw counts
df['Region'].value_counts(normalize=True)

,proportion
Region,
East,0.283333
South,0.266667
West,0.233333
North,0.216667


In [24]:
# Include missing values in the count (excluded by default)
df['PaymentMethod'].value_counts(dropna=False)

,count
PaymentMethod,
Credit Card,16
Cash,15
Bank Transfer,14
PayPal,10
NaN,5


**What the code does:** The first line counts how many orders came from each `Region`, sorted descending. The second does the same but as a proportion of the total (`normalize=True`, values sum to 1.0). The third counts `PaymentMethod` frequencies *including* missing values by passing `dropna=False`, so you can see how many `NaN`s exist alongside the real categories.

**Why it's used:** It's the standard way to detect **class imbalance** (e.g., are 90% of orders from one region and only 10% spread across the rest?), spot the most/least common categories, and see how much missing data exists in a column relative to real values.

**Expected output:** A Series indexed by each unique `Region` value, with counts that sum to 60 (or proportions summing to 1.0); the `PaymentMethod` version will show a `NaN` count of 5, matching the missing values introduced earlier.

**Where it's used in AI/ML / Data Analytics:** Essential for detecting **class imbalance** in a target variable before training a classifier (a heavily imbalanced target usually needs resampling or class-weighting), and for general categorical EDA in business analytics dashboards.